const SEED = [
  {date:'2026-07-15',opening:15930,income:4750,expenses:[['Caixa',1630],['Cartão Nubank',5200],['Cartão Itaú',2265],['Cartão Amazon',1775],['Tim',60],['Luz Apto',127],['Seguro Residencial',50]]},
  {date:'2026-07-30',income:4560,expenses:[['Combinaqui',40],['Condomínio',890],['Redfox',90]]},
  {date:'2026-08-15',opening:12900,income:5920,expenses:[['Caixa',1630],['Cartão Nubank',4500],['Cartão Itaú',2185],['Cartão Amazon',810],['Tim',60],['Luz Apto',130],['Seguro Residencial',50]]},
  {date:'2026-08-30',income:4500,expenses:[['Combinaqui',40],['Condomínio',650],['Redfox',90]]},
  {date:'2026-09-15',income:4700,expenses:[['Caixa',1630],['Cartão Nubank',3000],['Cartão Itaú',2100],['Cartão Amazon',800],['Tim',60],['Luz Apto',130],['Seguro Residencial',50]]},
  {date:'2026-09-30',income:0,expenses:[['Combinaqui',40],['Redfox',90]]},
  {date:'2026-10-15',income:0,expenses:[['Caixa',1630],['Seguro Residencial',50]]},
  {date:'2026-10-30',income:0,expenses:[['Combinaqui',40],['Redfox',90]]},
  {date:'2026-11-15',income:0,expenses:[['Caixa',1630],['Seguro Residencial',50]]},
  {date:'2026-11-30',income:0,expenses:[['Combinaqui',40],['Redfox',90]]},
  {date:'2026-12-15',income:0,expenses:[['Caixa',1630],['Seguro Residencial',50]]},
  {date:'2026-12-30',income:0,expenses:[['Combinaqui',40],['Redfox',90]]}
].map((p,i)=>({...p,id:'p'+i,expenses:p.expenses.map((e,j)=>({id:`e${i}_${j}`,category:e[0],amount:e[1],description:''}))}));

const clone=x=>JSON.parse(JSON.stringify(x));
let data=load(); let openId=null; let replicateSourceId=null;
function load(){try{return JSON.parse(localStorage.getItem('financePlan2026'))||clone(SEED)}catch{return clone(SEED)}}
function save(){localStorage.setItem('financePlan2026',JSON.stringify(data))}
function money(v){return (Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function shortDate(d){return new Date(d+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}
function calc(){let prev=null;return data.map((p,i)=>{const expense=p.expenses.reduce((s,e)=>s+(Number(e.amount)||0),0);const opening=(p.opening!=null&&p.opening!=='')?Number(p.opening):(prev??0);const final=opening+(Number(p.income)||0)+(Number(p.extra)||0)-expense;prev=final;return {...p,openingCalc:opening,totalExpense:expense,final}})}
function render(){const rows=calc(); renderKpis(rows);renderChart(rows);renderUpcoming(rows);renderPeriods(rows);enableAutomaticOpeningInputs(rows);addReplicateButtons(rows);populateModal(rows)}
function enableAutomaticOpeningInputs(rows){document.querySelectorAll('.period').forEach(period=>{const row=rows.find(item=>item.id===period.dataset.id);if(!row||row.opening!=null)return;const label=[...period.querySelectorAll('.income-row label')].find(item=>item.textContent.includes('Saldo inicial automático'));if(!label)return;const input=label.querySelector('input');input.disabled=false;input.type='number';input.step='0.01';input.value=row.openingCalc;input.onchange=()=>changeOpening(row.id,input.value)})}
function addReplicateButtons(rows){document.querySelectorAll('.period').forEach(period=>{const row=rows.find(item=>item.id===period.dataset.id),head=period.querySelector('.period-head');if(!row||!head||head.querySelector('.replicate-btn'))return;const button=document.createElement('button');button.type='button';button.className='btn replicate-btn';button.textContent='Replicar';button.setAttribute('aria-label',`Replicar despesas de ${shortDate(row.date)}`);button.onclick=event=>{event.stopPropagation();openReplicateModal(row.id)};head.insertBefore(button,head.querySelector('.toggle'))})}
function renderKpis(rows){const totalIncome=rows.reduce((s,p)=>s+(Number(p.income)||0)+(Number(p.extra)||0),0),totalExpense=rows.reduce((s,p)=>s+p.totalExpense,0),last=rows.at(-1)?.final||0,current=rows.find(p=>p.date>='2026-09-08')||rows[0];document.getElementById('kpis').innerHTML=`
<div class="card kpi"><div class="label">Saldo projetado final</div><div class="value ${last>=0?'positive':'negative'}">${money(last)}</div><div class="sub">Em ${shortDate(rows.at(-1).date)}</div></div>
<div class="card kpi"><div class="label">Receitas planejadas</div><div class="value positive">${money(totalIncome)}</div><div class="sub">Julho a dezembro/2026</div></div>
<div class="card kpi"><div class="label">Despesas planejadas</div><div class="value negative">${money(totalExpense)}</div><div class="sub">Todas as categorias</div></div>
<div class="card kpi"><div class="label">Próxima quinzena</div><div class="value ${current.final>=0?'positive':'negative'}">${money(current.final)}</div><div class="sub">Saldo após ${shortDate(current.date)}</div></div>`}
function renderChart(rows){const w=760,h=220,pad=34;const vals=rows.map(r=>r.final);const min=Math.min(...vals,0),max=Math.max(...vals,0),range=max-min||1;const x=i=>pad+i*(w-2*pad)/(rows.length-1),y=v=>h-pad-(v-min)*(h-2*pad)/range;let line=rows.map((r,i)=>`${i?'L':'M'} ${x(i)} ${y(r.final)}`).join(' ');let area=`M ${x(0)} ${h-pad} `+rows.map((r,i)=>`L ${x(i)} ${y(r.final)}`).join(' ')+` L ${x(rows.length-1)} ${h-pad} Z`;let labels=rows.map((r,i)=>`<text x="${x(i)}" y="${h-10}" text-anchor="middle" class="chart-label">${shortDate(r.date)}</text>`).join('');let pts=rows.map((r,i)=>`<circle class="point" cx="${x(i)}" cy="${y(r.final)}" r="4"><title>${shortDate(r.date)}: ${money(r.final)}</title></circle>`).join('');document.getElementById('chart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="grad" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#c7cad0" stop-opacity=".22"/><stop offset="100%" stop-color="#c7cad0" stop-opacity="0"/></linearGradient></defs><line x1="${pad}" y1="${y(0)}" x2="${w-pad}" y2="${y(0)}" class="axis"/><path d="${area}" class="area"/><path d="${line}" class="line"/>${pts}${labels}</svg>`}
function renderUpcoming(rows){const future=rows.filter(r=>r.date>='2026-09-08').slice(0,4);document.getElementById('nextLabel').textContent=future.length?`A partir de ${shortDate(future[0].date)}`:'';document.getElementById('upcoming').innerHTML=future.map(p=>`<div class="period-mini"><div class="row"><strong>${shortDate(p.date)}</strong><strong class="${p.final>=0?'positive':'negative'}">${money(p.final)}</strong></div><div class="row"><small>Receitas ${money(p.income)}</small><small>Despesas ${money(p.totalExpense)}</small></div></div>`).join('')||'<div class="empty">Nenhuma quinzena futura.</div>'}
function renderPeriods(rows){const q=document.getElementById('search').value.toLowerCase(),filter=document.getElementById('filter').value;const html=rows.filter(p=>filter==='all'||(filter==='positive'?p.final>=0:p.final<0)).map(p=>{const visible=p.expenses.filter(e=>!q||e.category.toLowerCase().includes(q)||e.description.toLowerCase().includes(q));return `<div class="period ${openId===p.id?'open':''}" data-id="${p.id}"><div class="period-head" onclick="togglePeriod('${p.id}')"><div><strong>${shortDate(p.date)}</strong><div style="color:var(--muted);font-size:12px">${new Date(p.date+'T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</div></div><div class="metric"><small>Saldo inicial</small><b>${money(p.openingCalc)}</b></div><div class="metric"><small>Receitas</small><b class="positive">${money(p.income)}</b></div><div class="metric hide-sm"><small>Despesas</small><b class="negative">${money(p.totalExpense)}</b></div><div class="metric hide-sm"><small>Saldo final</small><b class="${p.final>=0?'positive':'negative'}">${money(p.final)}</b></div><button class="toggle">⌄</button></div><div class="period-body"><div class="income-row"><label>Receita da quinzena<input type="number" step="0.01" value="${p.income}" onchange="changeIncome('${p.id}',this.value)"></label>${p.opening!=null?`<label>Saldo inicial manual<input type="number" step="0.01" value="${p.opening}" onchange="changeOpening('${p.id}',this.value)"></label>`:`<label>Saldo inicial automático<input disabled value="${money(p.openingCalc)}"></label>`}</div><div class="income-row"><label>Valores extras recebidos<input type="number" step="0.01" value="${p.extra||0}" onchange="changeExtra('${p.id}',this.value)"></label></div><div class="transactions">${visible.map(e=>`<div class="tx"><input value="${escapeHtml(e.category)}" onchange="changeExpense('${p.id}','${e.id}','category',this.value)"><input type="number" step="0.01" value="${e.amount}" onchange="changeExpense('${p.id}','${e.id}','amount',this.value)"><input class="category" value="${escapeHtml(e.description)}" placeholder="Descrição" onchange="changeExpense('${p.id}','${e.id}','description',this.value)"><button class="icon-btn" onclick="deleteExpense('${p.id}','${e.id}')">×</button></div>`).join('')||'<div class="empty" style="grid-column:1/-1">Nenhuma despesa encontrada.</div>'}</div><div class="add-line"><button class="btn" onclick="openModal('${p.id}')">+ Adicionar despesa nesta quinzena</button></div></div></div>`}).join('');document.getElementById('periods').innerHTML=html||'<div class="empty">Nenhuma quinzena atende ao filtro.</div>'}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.togglePeriod=id=>{openId=openId===id?null:id;render()};
window.changeIncome=(id,v)=>{data.find(p=>p.id===id).income=Number(v)||0;save();render()};
window.changeOpening=(id,v)=>{data.find(p=>p.id===id).opening=Number(v)||0;save();render()};
window.changeExtra=(id,v)=>{data.find(p=>p.id===id).extra=Number(v)||0;save();render()};
window.changeExpense=(pid,eid,key,v)=>{const e=data.find(p=>p.id===pid).expenses.find(x=>x.id===eid);e[key]=key==='amount'?(Number(v)||0):v;save();render()};
window.deleteExpense=(pid,eid)=>{const p=data.find(x=>x.id===pid);p.expenses=p.expenses.filter(x=>x.id!==eid);save();render()};
function populateModal(rows){document.getElementById('mPeriod').innerHTML=rows.map(p=>`<option value="${p.id}">${shortDate(p.date)}</option>`).join('')}
function openModal(pid){document.getElementById('modal').classList.add('show');if(pid)document.getElementById('mPeriod').value=pid;document.getElementById('mCategory').focus()}window.openModal=openModal;
function closeModal(){document.getElementById('modal').classList.remove('show');document.getElementById('mCategory').value='';document.getElementById('mAmount').value='';document.getElementById('mDescription').value=''}
function openReplicateModal(sourceId){replicateSourceId=sourceId;const destinations=data.filter(period=>period.id!==sourceId);document.getElementById('replicateDestination').innerHTML=destinations.map(period=>`<option value="${period.id}">${shortDate(period.date)}</option>`).join('');document.getElementById('replicateModal').classList.add('show');document.getElementById('replicateDestination').focus()}
function closeReplicateModal(){document.getElementById('replicateModal').classList.remove('show');replicateSourceId=null}
function replicateExpenses(){const source=data.find(period=>period.id===replicateSourceId),destination=data.find(period=>period.id===document.getElementById('replicateDestination').value);if(!source||!destination)return;destination.expenses=source.expenses.map((expense,index)=>({...clone(expense),id:`e${Date.now()}_${index}_${Math.random().toString(36).slice(2,7)}`}));save();openId=destination.id;closeReplicateModal();render()}
document.getElementById('newExpenseBtn').onclick=()=>openModal();document.getElementById('cancelModal').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.getElementById('saveExpense').onclick=()=>{const p=data.find(x=>x.id===document.getElementById('mPeriod').value),category=document.getElementById('mCategory').value.trim(),amount=Number(document.getElementById('mAmount').value)||0;if(!category||amount<=0){alert('Informe uma categoria e um valor maior que zero.');return}p.expenses.push({id:'e'+Date.now(),category,amount,description:document.getElementById('mDescription').value.trim()});save();openId=p.id;closeModal();render()};
document.getElementById('cancelReplicate').onclick=closeReplicateModal;document.getElementById('replicateModal').onclick=e=>{if(e.target.id==='replicateModal')closeReplicateModal()};document.getElementById('confirmReplicate').onclick=replicateExpenses;
document.getElementById('search').oninput=render;document.getElementById('filter').onchange=render;
document.getElementById('resetBtn').onclick=()=>{if(confirm('Restaurar os valores originais importados da planilha?')){data=clone(SEED);save();openId=null;render()}};
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='backup-financeiro-2026.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importBtn').onclick=()=>document.getElementById('fileInput').click();document.getElementById('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const obj=JSON.parse(r.result);if(!Array.isArray(obj.data))throw 0;data=obj.data;save();render();alert('Backup importado com sucesso.')}catch{alert('Arquivo de backup inválido.')}};r.readAsText(f);e.target.value=''};
render();
